[tool.codespell]
skip = "mu_rprog/sample-data/shakespeare.ndjson"
# ignore short words
ignore-regex = "\\b(.{1,4}|[A-Z]\\w*T)\\b"
ignore-words-list = "thirdparty,couldn"
quiet-level = 3

[tool.typos.default]

extend-ignore-identifiers-re = [
    "Indx",
    "TRU"
]
